### ISSUE TITLE
Cannot check for empty array

### ISSUE THREAD

**Issue by johnrhunt** [ubirak/rest-api-behat-extension#101]
When I use:

      And the JSON node "data" should be equal to "[]"

I get the following:

```
 And the JSON node "data" should be equal to "[]"            # Ubirak\RestApiBehatExtension\Json\JsonContext::theJsonNodeShouldBeEqualTo()
      array(0) is not equal to string(2) '[]'
      -Expected
      +Actual
      @@ -2 +2,2 @@
      -string(2) "[]"
      +array(0) {
      +} (Ubirak\RestApiBehatExtension\Json\WrongJsonExpectation)

```

I've tried, but I can't figure out why this is happening. Can anyone shed some light on this? It looks to me like an empty array needs to get translated into the string [] by Ubirak

**Comment by johnrhunt** [comment]
The JSON I was running this against was:
```
{
  "data": []
}
```

**Comment by tyx** [comment]
Hello !

You can use `the JSON array node "data" should have 0 element`

Hope it fits your need

**Comment by tyx** [comment]
But yes we could create a proxy around the empty use case ! Looks fine for me

**Comment by johnrhunt** [comment]
I followed @tyx 's recommendation - it worked lovely thank you.

**Comment by shouze** [comment]
@johnrhunt so, closing it
